// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/investor/_middleware.ts";
import * as $3 from "./routes/api/investor/end.ts";
import * as $4 from "./routes/api/investor/names/last.ts";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/login.ts";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/login.tsx";
import * as $10 from "./routes/posts/[id]/edit.tsx";
import * as $11 from "./routes/posts/[id]/index.tsx";
import * as $12 from "./routes/posts/new.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LoginForm.tsx";
import * as $$2 from "./islands/investor/List.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/investor/_middleware.ts": $2,
    "./routes/api/investor/end.ts": $3,
    "./routes/api/investor/names/last.ts": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/login.ts": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/login.tsx": $9,
    "./routes/posts/[id]/edit.tsx": $10,
    "./routes/posts/[id]/index.tsx": $11,
    "./routes/posts/new.tsx": $12,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LoginForm.tsx": $$1,
    "./islands/investor/List.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
